sudo: false

language: php

php:
  - 7.1.1 #@todo set 7.1 after release 7.1.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - cd amphp

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - php bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls dev-master
  - php bin/coveralls -v
  
cache:
  directories:
    - $HOME/.composer/cache

