version: '2'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
     - redis
    environment:
     - REDIS_URI=tcp://redis:6379
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
     - /data/backlog/redis:/data

