version: '2'
services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - redis
    environment:
     - REDIS_URI=tcp://redis:6379
    volumes:
     - /var/www/.well-known:/application/web/.well-known
     - /etc/letsencrypt:/etc/letsencrypt
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
     - /data/backlog/redis:/data

