System.register(['handlebars'], function(exports_1) {
    var hbs;
    var template;
    return {
        setters:[
            function (hbs_1) {
                hbs = hbs_1;
            }],
        execute: function() {
            exports_1("template", template = hbs.compile("\n    <div class=\"mdl-card__title mdl-card--expand backlog-story-title\">\n        {{#if state.showText}}\n            <div class=\"backlog-story-title-block\">\n                {{^state.isEditMode}}\n                    <h4>{{ story.text }}</h4>\n                {{/state.isEditMode}}\n\n                {{#state.isEditMode}}\n                    <div>\n                        <textarea\n                                id=\"text\"\n                                name=\"text\"\n                                class=\"mdl-textfield__input\">{{story.text}}</textarea>\n                    </div>\n                {{/state.isEditMode}}\n            </div>\n        {{else}}\n            <div class=\"backlog-story-title-block\">\n                <h5>\u0422\u0440\u0435\u0431\u043E\u0432\u0430\u043D\u0438\u044F</h5>\n                <ul class=\"mdl-list\">\n                    <li *ngFor=\"#requirement of story.requirements\" class=\"mdl-list__item\">\n                        <span class=\"mdl-list__item-primary-content\">\n                            <i class=\"material-icons\">crop_original</i>\n                            {{requirement}}\n                        </span>\n                        <a class=\"mdl-list__item-secondary-action\"><i class=\"material-icons\">star</i></a>\n                    </li>\n                </ul>\n            </div>\n        {{/if}}\n    </div>\n\n    {{^if state.isEditMode}}\n        <div class=\"mdl-card__actions mdl-card--border\">\n            <a class=\"edit mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\">\n                \u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C\n            </a>\n            <a class=\"requirements mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\">\n                \u0422\u0440\u0435\u0431\u043E\u0432\u0430\u043D\u0438\u044F\n            </a>\n        </div>\n    {{else}}\n        <div class=\"mdl-card__actions mdl-card--border\">\n            <a class=\"save mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\">\n                \u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C\n            </a>\n            <a class=\"cancel mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect\">\n                \u041E\u0442\u043C\u0435\u043D\u0430\n            </a>\n        </div>\n    {{/if}}\n\n    <div class=\"mdl-card__menu\">\n        <button class=\"mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect\">\n            <i class=\"material-icons\">assignment_late</i>\n        </button>\n    </div>\n"));
            exports_1("default",template);
        }
    }
});
//# sourceMappingURL=story.js.map