services:
  _defaults:
    autowire: true
    tags: [ backlog.action ]

  Fedot\Backlog\Action\CreateStory: ~
  Fedot\Backlog\Action\DeleteStory: ~
  Fedot\Backlog\Action\EditStory: ~
  Fedot\Backlog\Action\MoveStory: ~
  Fedot\Backlog\Action\MarkStoryAsCompleted: ~
  Fedot\Backlog\Action\GetStories: ~

  Fedot\Backlog\Action\Project\GetProjects: ~
  Fedot\Backlog\Action\Project\ProjectCreate: ~
  Fedot\Backlog\Action\Project\Share\ShareProject: ~

  Fedot\Backlog\Action\User\Registration: ~
  Fedot\Backlog\Action\LoginUsernamePassword: ~
  Fedot\Backlog\Action\LoginToken: ~

  Fedot\Backlog\Action\Ping: ~