apiVersion: v1
kind: PersistentVolume
metadata:
  name: gv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv1
    readOnly: false

