---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backlog-web-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: backlog
        role: web-server
      annotations:
        deployVersion: "14"
    spec:
      containers:
        - name: backlog-web-server
          image: fedot/backlog-web-server
          ports:
          - containerPort: 80
          env:
            - name: WEBSERVER_PORT
              value: "80"
            - name: REDIS_DATABASE
              value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: backlog-web-server
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: backlog
    role: web-server

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backlog
spec:
  rules:
  - host: k8s-backlog.fedot.name
    http:
      paths:
      - backend:
          serviceName: backlog-web-server
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backlog-tls
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - k8s-backlog.fedot.name
    secretName: backlog-tls
  rules:
  - host: k8s-backlog.fedot.name
    http:
      paths:
      - backend:
          serviceName: backlog-web-server
          servicePort: 80
