parameters:

services:
  backlog.web-socket.server:
    class: Fedot\Backlog\WebSocketServer
    autowire: true

  backlog.infrastructure.runner-factory:
    class: Fedot\Backlog\Infrastructure\Middleware\RunnerFactory
    autowire: true

  backlog.middleware.payload-parser:
    class: Fedot\Backlog\Middleware\PayloadParser
    autowire: true
    tags:
      - { name: backlog.middleware, priority: 1 }

  backlog.middleware.request-processor:
    class: Fedot\Backlog\Middleware\RequestProcessor
    autowire: true
    tags:
      - { name: backlog.middleware, priority: 5 }

  serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments: ['', '']

  serializer.normolizer.object:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      - ''
      - ''
      - ''
      - '@property_info'
    tags:
      - { name: serializer.normalizer, priority: 0 }

  serializer.encoder.json:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
    tags:
      - { name: serializer.encoder, priority: 0 }

  property_info:
    class: Symfony\Component\PropertyInfo\PropertyInfoExtractor
    arguments: ['', '', '', '']

  property_info.type_extractor.php-doc:
    class: Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor
    tags:
      - { name: property_info.type_extractor, priority: 0 }
