imports:
    - { resource: services/actions.yml }

parameters:
  backlog.data-storage.redis.client.uri: '%env(REDIS_URI)%'
  env(REDIS_URI): tcp://%env(REDIS_SINGLE_SERVICE_HOST)%:6379?database=%env(REDIS_DATABASE)%
  webserver-port: '%env(WEBSERVER_PORT)%'
  env(WEBSERVER_PORT): 8080
  env(REDIS_SINGLE_SERVICE_HOST): localhost #ugly hack for fix not resolve domain in k8s
  env(REDIS_DATABASE): 11

services:
  backlog.infrastructure.runner-factory:
    class: Fedot\Backlog\Infrastructure\Middleware\RunnerFactory
    autowire: true

  backlog.serializer-service:
    class: Fedot\Backlog\SerializerService
    arguments:
      - "@serializer"

  backlog.action.manager:
    class: Fedot\Backlog\ActionManager

  serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments: ['', '']
    autowiring_types:
      - Symfony\Component\Serializer\Normalizer\NormalizerInterface
      - Symfony\Component\Serializer\Normalizer\DenormalizerInterface
      - Symfony\Component\Serializer\SerializerInterface

  Fedot\Backlog\ExcludePluralPropertiesObjectNormalizer:
    arguments:
      - '@Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory'
      - null
      - null
      - '@property_info'
    tags:
      - { name: serializer.normalizer, priority: 0 }

  Symfony\Component\Serializer\Encoder\JsonEncoder:
    tags:
      - { name: serializer.encoder, priority: 0 }

  property_info:
    class: Symfony\Component\PropertyInfo\PropertyInfoExtractor
    arguments: ['', '', '', '']

  Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor:
    tags:
      - { name: property_info.type_extractor, priority: 0 }

  Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory:
    autowire: true

  Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader:
    autowire: true

  Amp\Redis\Client:
    arguments:
      - "%backlog.data-storage.redis.client.uri%"

  Fedot\Backlog\Middleware\PayloadParser:
    autowire: true
    tags:
      - { name: backlog.middleware, priority: 5 }

  Fedot\Backlog\Middleware\ActionProcessor:
    autowire: true
    tags:
      - { name: backlog.middleware, priority: 0 }

  Fedot\Backlog\WebSocketServer:
    autowire: true
  Fedot\DataMapper\Metadata\Driver\AnnotationDriver:
    autowire: true
  Symfony\Component\PropertyAccess\PropertyAccessor:
    autowire: true
  Doctrine\Common\Annotations\AnnotationReader:
    autowire: true
  Fedot\DataMapper\Redis\ModelManager:
    autowire: true
  Fedot\Backlog\MessageProcessor:
    autowire: true
  Ramsey\Uuid\UuidFactory:
    autowire: true
  Metadata\MetadataFactory:
    autowire: true
  Doctrine\Instantiator\Instantiator:
    autowire: true
