imports:
    - { resource: parameters.php }
    - { resource: services/actions.yml }

parameters:

services:
  backlog.web-socket.server:
    class: Fedot\Backlog\WebSocketServer
    autowire: true

  backlog.infrastructure.runner-factory:
    class: Fedot\Backlog\Infrastructure\Middleware\RunnerFactory
    autowire: true

  backlog.serializer-service:
    class: Fedot\Backlog\SerializerService
    arguments:
      - "@serializer"

  backlog.middleware.payload-parser:
    class: Fedot\Backlog\Middleware\PayloadParser
    autowire: true
    tags:
      - { name: backlog.middleware, priority: 5 }

  backlog.middleware.request-processor:
    class: Fedot\Backlog\Middleware\ActionProcessor
    autowire: true
    tags:
      - { name: backlog.middleware, priority: 0 }

  backlog.action.manager:
    class: Fedot\Backlog\Action\ActionManager

  backlog.data-storage.redis.key-generator:
    class: Fedot\DataStorage\Redis\KeyGenerator

  backlog.data-storage.redis.fetch-manager:
    class: Fedot\DataStorage\Redis\FetchManager
    autowire: true

  backlog.data-storage.redis.persist-manager:
    class: Fedot\DataStorage\Redis\PersistManager
    autowire: true

  backlog.data-storage.redis.relationship-manager:
    class: Fedot\DataStorage\Redis\RelationshipManager
    autowire: true

  backlog.data-storage.redis.client:
    class: Amp\Redis\Client
    arguments:
      - "%backlog.data-storage.redis.client.uri%"

  serializer:
    class: Symfony\Component\Serializer\Serializer
    arguments: ['', '']
    autowiring_types:
      - Symfony\Component\Serializer\Normalizer\NormalizerInterface
      - Symfony\Component\Serializer\Normalizer\DenormalizerInterface
      - Symfony\Component\Serializer\SerializerInterface

  serializer.normalizer.object:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments:
      - null
      - null
      - null
      - '@property_info'
    tags:
      - { name: serializer.normalizer, priority: 0 }

  serializer.encoder.json:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
    tags:
      - { name: serializer.encoder, priority: 0 }

  property_info:
    class: Symfony\Component\PropertyInfo\PropertyInfoExtractor
    arguments: ['', '', '', '']

  property_info.type_extractor.php-doc:
    class: Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor
    tags:
      - { name: property_info.type_extractor, priority: 0 }
