services:
    backlog.repository.stories:
        class: BacklogBundle\Document\StoriesRepository
        factory: ["@doctrine_mongodb", getRepository]
        arguments:
            - BacklogBundle:Story
