services:
    backlog.repository.stories:
        class: BacklogBundle\Document\Story\StoriesRepository
        factory: ["@doctrine_mongodb", getRepository]
        arguments:
            - BacklogBundle:Story\Story
