services:
    backlog.repository.stories:
        class: BacklogBundle\Document\StoriesRepository
        factory_service: doctrine_mongodb
        factory_method: getRepository
        arguments:
            - BacklogBundle\Document\Story
