services:
    sensio_framework_extra.converter.doctrine.orm:
        class: %sensio_framework_extra.converter.doctrine.class%
        arguments: ["@doctrine_mongodb"]
        tags:
            - { name: request.param_converter, converter: doctrine.orm }

    backlog.serializer.handler.collection:
        class: BacklogBundle\CollectionHandler
        arguments:
            - "@jms_serializer.metadata_factory"
        tags:
            - { name: "jms_serializer.handler", type: "Collection", format: "json", direction: "serialization" }
            - { name: "jms_serializer.event_listener", event: "serializer.pre_serialize" }

    backlog.repository.stories:
        class: BacklogBundle\Document\Story\StoriesRepository
        factory: ["@doctrine_mongodb", getRepository]
        arguments:
            - BacklogBundle:Story\Story

    backlog.repository.requirements:
        class: BacklogBundle\Document\Requirement\RequirementsRepository
        factory: ["@doctrine_mongodb", getRepository]
        arguments:
            - BacklogBundle:Requirement\Requirement
